language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: zpace
  password:
    secure: VCZ6HLe2VSt/wrsh37yrt5CnvQ29guTw+nloenWZWDrbT8hlyuwqrSvsSIwji0fVoGXyJzlSSnWAagqpnbDRZtMzR8iB6otAU4VR6kBuUu4hi63N75gQRbTqfipjFAbz6LcSj5ohjo0SxNjyBuVB84GHz5iko4ZA0pQPv7LMcjGa7WFO27zZhVhLhrCR4sBOTyDRgQ3j0mNz0ezh0F5AtlWX6zYs9aPWqAy3FZFXyCZiRpqYOde7MFl71RHj30Lkpl4OQ6WUkZmw6MG1N70zgkMVfrXhWFjNqS5BFeBNWhIBifSptuiuiE3dzcCAPOTakJZUPbIOhpXS2iBrMQtk0w2MTNkeiGB6DU0mS2WFzP6hPxAMQrPlEReVjWrAkmqnZL3O4H7F7GU0cP4LAl33K9DZRIM4sXRiJjs5OoMYPpV8sklzDNlC1fsnwJXggUrdLGJ6HnChnckoNJIXO56fUtamqIBMaiAFyH8iHpNx2+Jl3Xzfmjop5YRCqwizqXdlPOaJVGAWuFphLRitMiaHIcHnqV9UI0HuGJP7+wExlqfjOY5MY18jjJWXw4/7B38Iy4yOxgGqoGm1P1aJlCzOmI9iy/G+UX5YStxlC3RPDykQTOKAMScCn19lKKwUDWtLDyKdJOQyQ0K7JN9j5SiogMZVsO/ogp1lc/v660hU3LQ=
  on:
    tags: true
    repo: zpace/pcabc
    python: 3.8
